version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: postdb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  # Node API service
  api:
    container_name: postapp
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}